package com.ayantsoft.expm.hibernate.pojo;
// Generated 10 Jun, 2017 2:20:04 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BankInternal generated by hbm2java
 */
@Entity
@Table(name = "bank_internal", catalog = "expm")
public class BankInternal implements java.io.Serializable {

	private Integer id;
	private String bankName;
	private String accountNo;
	private Set<BankInternalCard> bankInternalCards = new HashSet<BankInternalCard>(0);
	private Set<ChequeNo> chequeNos = new HashSet<ChequeNo>(0);

	public BankInternal() {
	}

	public BankInternal(String bankName, String accountNo, Set<BankInternalCard> bankInternalCards,
			Set<ChequeNo> chequeNos) {
		this.bankName = bankName;
		this.accountNo = accountNo;
		this.bankInternalCards = bankInternalCards;
		this.chequeNos = chequeNos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "bank_name", length = 200)
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Column(name = "account_no", length = 100)
	public String getAccountNo() {
		return this.accountNo;
	}

	public void setAccountNo(String accountNo) {
		this.accountNo = accountNo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bankInternal")
	public Set<BankInternalCard> getBankInternalCards() {
		return this.bankInternalCards;
	}

	public void setBankInternalCards(Set<BankInternalCard> bankInternalCards) {
		this.bankInternalCards = bankInternalCards;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bankInternal")
	public Set<ChequeNo> getChequeNos() {
		return this.chequeNos;
	}

	public void setChequeNos(Set<ChequeNo> chequeNos) {
		this.chequeNos = chequeNos;
	}

}
