package com.ayantsoft.expm.hibernate.pojo;
// Generated 10 Jun, 2017 2:20:04 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Bank generated by hbm2java
 */
@Entity
@Table(name = "bank", catalog = "expm")
public class Bank implements java.io.Serializable {

	private Integer bankId;
	private Vendor vendor;
	private String bankAccountNo;
	private String bankIfsc;
	private String bankName;
	private String bankBranch;
	private String bankAccountType;
	private Boolean primaryAccount;
	private String payeeName;

	public Bank() {
	}

	public Bank(Vendor vendor) {
		this.vendor = vendor;
	}

	public Bank(Vendor vendor, String bankAccountNo, String bankIfsc, String bankName, String bankBranch,
			String bankAccountType, Boolean primaryAccount, String payeeName) {
		this.vendor = vendor;
		this.bankAccountNo = bankAccountNo;
		this.bankIfsc = bankIfsc;
		this.bankName = bankName;
		this.bankBranch = bankBranch;
		this.bankAccountType = bankAccountType;
		this.primaryAccount = primaryAccount;
		this.payeeName = payeeName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "bankId", unique = true, nullable = false)
	public Integer getBankId() {
		return this.bankId;
	}

	public void setBankId(Integer bankId) {
		this.bankId = bankId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vendor_id", nullable = false)
	public Vendor getVendor() {
		return this.vendor;
	}

	public void setVendor(Vendor vendor) {
		this.vendor = vendor;
	}

	@Column(name = "bank_account_no", length = 100)
	public String getBankAccountNo() {
		return this.bankAccountNo;
	}

	public void setBankAccountNo(String bankAccountNo) {
		this.bankAccountNo = bankAccountNo;
	}

	@Column(name = "bank_ifsc", length = 100)
	public String getBankIfsc() {
		return this.bankIfsc;
	}

	public void setBankIfsc(String bankIfsc) {
		this.bankIfsc = bankIfsc;
	}

	@Column(name = "bank_name", length = 100)
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Column(name = "bank_branch", length = 200)
	public String getBankBranch() {
		return this.bankBranch;
	}

	public void setBankBranch(String bankBranch) {
		this.bankBranch = bankBranch;
	}

	@Column(name = "bank_account_type", length = 7)
	public String getBankAccountType() {
		return this.bankAccountType;
	}

	public void setBankAccountType(String bankAccountType) {
		this.bankAccountType = bankAccountType;
	}

	@Column(name = "primary_account")
	public Boolean getPrimaryAccount() {
		return this.primaryAccount;
	}

	public void setPrimaryAccount(Boolean primaryAccount) {
		this.primaryAccount = primaryAccount;
	}

	@Column(name = "payee_name", length = 45)
	public String getPayeeName() {
		return this.payeeName;
	}

	public void setPayeeName(String payeeName) {
		this.payeeName = payeeName;
	}

}
