package com.ayantsoft.expm.hibernate.pojo;
// Generated 10 Jun, 2017 2:20:04 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CardBook generated by hbm2java
 */
@Entity
@Table(name = "card_book", catalog = "expm")
public class CardBook implements java.io.Serializable {

	private Integer txnId;
	private BankInternalCard bankInternalCard;
	private PaymentDetail paymentDetail;
	private User user;
	private String description;
	private BigDecimal amount;
	private Date cardSwipedDate;
	private String cardSwipedBy;
	private Date entryDate;

	public CardBook() {
	}

	public CardBook(User user, String description, BigDecimal amount, Date cardSwipedDate, String cardSwipedBy,
			Date entryDate) {
		this.user = user;
		this.description = description;
		this.amount = amount;
		this.cardSwipedDate = cardSwipedDate;
		this.cardSwipedBy = cardSwipedBy;
		this.entryDate = entryDate;
	}

	public CardBook(BankInternalCard bankInternalCard, PaymentDetail paymentDetail, User user, String description,
			BigDecimal amount, Date cardSwipedDate, String cardSwipedBy, Date entryDate) {
		this.bankInternalCard = bankInternalCard;
		this.paymentDetail = paymentDetail;
		this.user = user;
		this.description = description;
		this.amount = amount;
		this.cardSwipedDate = cardSwipedDate;
		this.cardSwipedBy = cardSwipedBy;
		this.entryDate = entryDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "txn_id", unique = true, nullable = false)
	public Integer getTxnId() {
		return this.txnId;
	}

	public void setTxnId(Integer txnId) {
		this.txnId = txnId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bank_internal_card_id")
	public BankInternalCard getBankInternalCard() {
		return this.bankInternalCard;
	}

	public void setBankInternalCard(BankInternalCard bankInternalCard) {
		this.bankInternalCard = bankInternalCard;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "payment_id")
	public PaymentDetail getPaymentDetail() {
		return this.paymentDetail;
	}

	public void setPaymentDetail(PaymentDetail paymentDetail) {
		this.paymentDetail = paymentDetail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "entry_by", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "description", nullable = false, length = 245)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "amount", nullable = false, precision = 10)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "card_swiped_date", nullable = false, length = 10)
	public Date getCardSwipedDate() {
		return this.cardSwipedDate;
	}

	public void setCardSwipedDate(Date cardSwipedDate) {
		this.cardSwipedDate = cardSwipedDate;
	}

	@Column(name = "card_swiped_by", nullable = false, length = 100)
	public String getCardSwipedBy() {
		return this.cardSwipedBy;
	}

	public void setCardSwipedBy(String cardSwipedBy) {
		this.cardSwipedBy = cardSwipedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "entry_date", nullable = false, length = 10)
	public Date getEntryDate() {
		return this.entryDate;
	}

	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}

}
