package com.ayantsoft.expm.hibernate.pojo;
// Generated 10 Jun, 2017 2:20:04 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CashBook generated by hbm2java
 */
@Entity
@Table(name = "cash_book", catalog = "expm")
public class CashBook implements java.io.Serializable {

	private Integer txnId;
	private PaymentDetail paymentDetail;
	private User user;
	private String description;
	private String txnType;
	private Date entryDate;
	private BigDecimal credit;
	private BigDecimal debit;
	private Set<CashDocuments> cashDocumentses = new HashSet<CashDocuments>(0);

	public CashBook() {
	}

	public CashBook(User user, String description, String txnType, Date entryDate) {
		this.user = user;
		this.description = description;
		this.txnType = txnType;
		this.entryDate = entryDate;
	}

	public CashBook(PaymentDetail paymentDetail, User user, String description, String txnType, Date entryDate,
			BigDecimal credit, BigDecimal debit, Set<CashDocuments> cashDocumentses) {
		this.paymentDetail = paymentDetail;
		this.user = user;
		this.description = description;
		this.txnType = txnType;
		this.entryDate = entryDate;
		this.credit = credit;
		this.debit = debit;
		this.cashDocumentses = cashDocumentses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "txn_id", unique = true, nullable = false)
	public Integer getTxnId() {
		return this.txnId;
	}

	public void setTxnId(Integer txnId) {
		this.txnId = txnId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "payment_id")
	public PaymentDetail getPaymentDetail() {
		return this.paymentDetail;
	}

	public void setPaymentDetail(PaymentDetail paymentDetail) {
		this.paymentDetail = paymentDetail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "entry_by", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "description", nullable = false, length = 245)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "txn_type", nullable = false, length = 7)
	public String getTxnType() {
		return this.txnType;
	}

	public void setTxnType(String txnType) {
		this.txnType = txnType;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "entry_date", nullable = false, length = 10)
	public Date getEntryDate() {
		return this.entryDate;
	}

	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}

	@Column(name = "credit", precision = 10)
	public BigDecimal getCredit() {
		return this.credit;
	}

	public void setCredit(BigDecimal credit) {
		this.credit = credit;
	}

	@Column(name = "debit", precision = 10)
	public BigDecimal getDebit() {
		return this.debit;
	}

	public void setDebit(BigDecimal debit) {
		this.debit = debit;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cashBook")
	public Set<CashDocuments> getCashDocumentses() {
		return this.cashDocumentses;
	}

	public void setCashDocumentses(Set<CashDocuments> cashDocumentses) {
		this.cashDocumentses = cashDocumentses;
	}

}
