package com.ayantsoft.expm.hibernate.pojo;
// Generated 10 Jun, 2017 2:20:04 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ChequeNo generated by hbm2java
 */
@Entity
@Table(name = "cheque_no", catalog = "expm")
public class ChequeNo implements java.io.Serializable {

	private String chequeNo;
	private BankInternal bankInternal;
	private Boolean isIssued;

	public ChequeNo() {
	}

	public ChequeNo(String chequeNo) {
		this.chequeNo = chequeNo;
	}

	public ChequeNo(String chequeNo, BankInternal bankInternal, Boolean isIssued) {
		this.chequeNo = chequeNo;
		this.bankInternal = bankInternal;
		this.isIssued = isIssued;
	}

	@Id

	@Column(name = "cheque_no", unique = true, nullable = false, length = 100)
	public String getChequeNo() {
		return this.chequeNo;
	}

	public void setChequeNo(String chequeNo) {
		this.chequeNo = chequeNo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bank_internal_id")
	public BankInternal getBankInternal() {
		return this.bankInternal;
	}

	public void setBankInternal(BankInternal bankInternal) {
		this.bankInternal = bankInternal;
	}

	@Column(name = "is_issued")
	public Boolean getIsIssued() {
		return this.isIssued;
	}

	public void setIsIssued(Boolean isIssued) {
		this.isIssued = isIssued;
	}

}
