package com.ayantsoft.expm.hibernate.pojo;
// Generated 10 Jun, 2017 2:20:04 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ChequeBook generated by hbm2java
 */
@Entity
@Table(name = "cheque_book", catalog = "expm")
public class ChequeBook implements java.io.Serializable {

	private String chequeNo;
	private PaymentDetail paymentDetail;
	private User user;
	private String description;
	private String payeeName;
	private Date payableDate;
	private BigDecimal amount;
	private boolean isAccountPayable;
	private String chequeStatus;
	private Date entryDate;

	public ChequeBook() {
	}

	public ChequeBook(String chequeNo, User user, String description, String payeeName, Date payableDate,
			BigDecimal amount, boolean isAccountPayable, String chequeStatus, Date entryDate) {
		this.chequeNo = chequeNo;
		this.user = user;
		this.description = description;
		this.payeeName = payeeName;
		this.payableDate = payableDate;
		this.amount = amount;
		this.isAccountPayable = isAccountPayable;
		this.chequeStatus = chequeStatus;
		this.entryDate = entryDate;
	}

	public ChequeBook(String chequeNo, PaymentDetail paymentDetail, User user, String description, String payeeName,
			Date payableDate, BigDecimal amount, boolean isAccountPayable, String chequeStatus, Date entryDate) {
		this.chequeNo = chequeNo;
		this.paymentDetail = paymentDetail;
		this.user = user;
		this.description = description;
		this.payeeName = payeeName;
		this.payableDate = payableDate;
		this.amount = amount;
		this.isAccountPayable = isAccountPayable;
		this.chequeStatus = chequeStatus;
		this.entryDate = entryDate;
	}

	@Id

	@Column(name = "cheque_no", unique = true, nullable = false, length = 100)
	public String getChequeNo() {
		return this.chequeNo;
	}

	public void setChequeNo(String chequeNo) {
		this.chequeNo = chequeNo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "payment_id")
	public PaymentDetail getPaymentDetail() {
		return this.paymentDetail;
	}

	public void setPaymentDetail(PaymentDetail paymentDetail) {
		this.paymentDetail = paymentDetail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "entry_by", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "description", nullable = false, length = 245)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "payee_name", nullable = false, length = 45)
	public String getPayeeName() {
		return this.payeeName;
	}

	public void setPayeeName(String payeeName) {
		this.payeeName = payeeName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "payable_date", nullable = false, length = 10)
	public Date getPayableDate() {
		return this.payableDate;
	}

	public void setPayableDate(Date payableDate) {
		this.payableDate = payableDate;
	}

	@Column(name = "amount", nullable = false, precision = 10)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "is_account_payable", nullable = false)
	public boolean isIsAccountPayable() {
		return this.isAccountPayable;
	}

	public void setIsAccountPayable(boolean isAccountPayable) {
		this.isAccountPayable = isAccountPayable;
	}

	@Column(name = "cheque_status", nullable = false, length = 8)
	public String getChequeStatus() {
		return this.chequeStatus;
	}

	public void setChequeStatus(String chequeStatus) {
		this.chequeStatus = chequeStatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "entry_date", nullable = false, length = 10)
	public Date getEntryDate() {
		return this.entryDate;
	}

	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}

}
