package com.ayantsoft.expm.hibernate.pojo;
// Generated 10 Jun, 2017 2:20:04 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NeftBook generated by hbm2java
 */
@Entity
@Table(name = "neft_book", catalog = "expm")
public class NeftBook implements java.io.Serializable {

	private Integer txnId;
	private PaymentDetail paymentDetail;
	private User userByNeftBy;
	private User userByEntryBy;
	private String description;
	private String payeeName;
	private String payeeBankName;
	private String payeeBankIfsc;
	private String payeeBankBranch;
	private BigDecimal amount;
	private String neftStatus;
	private Date neftDate;
	private Date entryDate;

	public NeftBook() {
	}

	public NeftBook(PaymentDetail paymentDetail, User userByEntryBy, String description, String payeeName,
			String payeeBankName, String payeeBankIfsc, BigDecimal amount, Date neftDate, Date entryDate) {
		this.paymentDetail = paymentDetail;
		this.userByEntryBy = userByEntryBy;
		this.description = description;
		this.payeeName = payeeName;
		this.payeeBankName = payeeBankName;
		this.payeeBankIfsc = payeeBankIfsc;
		this.amount = amount;
		this.neftDate = neftDate;
		this.entryDate = entryDate;
	}

	public NeftBook(PaymentDetail paymentDetail, User userByNeftBy, User userByEntryBy, String description,
			String payeeName, String payeeBankName, String payeeBankIfsc, String payeeBankBranch, BigDecimal amount,
			String neftStatus, Date neftDate, Date entryDate) {
		this.paymentDetail = paymentDetail;
		this.userByNeftBy = userByNeftBy;
		this.userByEntryBy = userByEntryBy;
		this.description = description;
		this.payeeName = payeeName;
		this.payeeBankName = payeeBankName;
		this.payeeBankIfsc = payeeBankIfsc;
		this.payeeBankBranch = payeeBankBranch;
		this.amount = amount;
		this.neftStatus = neftStatus;
		this.neftDate = neftDate;
		this.entryDate = entryDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "txn_id", unique = true, nullable = false)
	public Integer getTxnId() {
		return this.txnId;
	}

	public void setTxnId(Integer txnId) {
		this.txnId = txnId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "payment_id", nullable = false)
	public PaymentDetail getPaymentDetail() {
		return this.paymentDetail;
	}

	public void setPaymentDetail(PaymentDetail paymentDetail) {
		this.paymentDetail = paymentDetail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "neft_by")
	public User getUserByNeftBy() {
		return this.userByNeftBy;
	}

	public void setUserByNeftBy(User userByNeftBy) {
		this.userByNeftBy = userByNeftBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "entry_by", nullable = false)
	public User getUserByEntryBy() {
		return this.userByEntryBy;
	}

	public void setUserByEntryBy(User userByEntryBy) {
		this.userByEntryBy = userByEntryBy;
	}

	@Column(name = "description", nullable = false, length = 245)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "payee_name", nullable = false, length = 45)
	public String getPayeeName() {
		return this.payeeName;
	}

	public void setPayeeName(String payeeName) {
		this.payeeName = payeeName;
	}

	@Column(name = "payee_bank_name", nullable = false, length = 45)
	public String getPayeeBankName() {
		return this.payeeBankName;
	}

	public void setPayeeBankName(String payeeBankName) {
		this.payeeBankName = payeeBankName;
	}

	@Column(name = "payee_bank_ifsc", nullable = false, length = 45)
	public String getPayeeBankIfsc() {
		return this.payeeBankIfsc;
	}

	public void setPayeeBankIfsc(String payeeBankIfsc) {
		this.payeeBankIfsc = payeeBankIfsc;
	}

	@Column(name = "payee_bank_branch", length = 45)
	public String getPayeeBankBranch() {
		return this.payeeBankBranch;
	}

	public void setPayeeBankBranch(String payeeBankBranch) {
		this.payeeBankBranch = payeeBankBranch;
	}

	@Column(name = "amount", nullable = false, precision = 10)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "neft_status", length = 8)
	public String getNeftStatus() {
		return this.neftStatus;
	}

	public void setNeftStatus(String neftStatus) {
		this.neftStatus = neftStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "neft_date", nullable = false, length = 19)
	public Date getNeftDate() {
		return this.neftDate;
	}

	public void setNeftDate(Date neftDate) {
		this.neftDate = neftDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "entry_date", nullable = false, length = 10)
	public Date getEntryDate() {
		return this.entryDate;
	}

	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}

}
