package com.ayantsoft.expm.hibernate.pojo;
// Generated 10 Jun, 2017 2:20:04 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PaymentsDocuments generated by hbm2java
 */
@Entity
@Table(name = "payments_documents", catalog = "expm")
public class PaymentsDocuments implements java.io.Serializable {

	private Integer id;
	private PaymentDetail paymentDetail;
	private String fileName;
	private String filePath;
	private String contentType;
	private Date createdDate;
	private String extension;

	public PaymentsDocuments() {
	}

	public PaymentsDocuments(PaymentDetail paymentDetail, String fileName, String filePath, String contentType,
			Date createdDate) {
		this.paymentDetail = paymentDetail;
		this.fileName = fileName;
		this.filePath = filePath;
		this.contentType = contentType;
		this.createdDate = createdDate;
	}

	public PaymentsDocuments(PaymentDetail paymentDetail, String fileName, String filePath, String contentType,
			Date createdDate, String extension) {
		this.paymentDetail = paymentDetail;
		this.fileName = fileName;
		this.filePath = filePath;
		this.contentType = contentType;
		this.createdDate = createdDate;
		this.extension = extension;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "payment_id", nullable = false)
	public PaymentDetail getPaymentDetail() {
		return this.paymentDetail;
	}

	public void setPaymentDetail(PaymentDetail paymentDetail) {
		this.paymentDetail = paymentDetail;
	}

	@Column(name = "file_name", nullable = false, length = 100)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "file_path", nullable = false, length = 300)
	public String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	@Column(name = "content_type", nullable = false, length = 100)
	public String getContentType() {
		return this.contentType;
	}

	public void setContentType(String contentType) {
		this.contentType = contentType;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", nullable = false, length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "extension", length = 45)
	public String getExtension() {
		return this.extension;
	}

	public void setExtension(String extension) {
		this.extension = extension;
	}

}
