package com.ayantsoft.expm.hibernate.pojo;
// Generated 10 Jun, 2017 2:20:04 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Vendor generated by hbm2java
 */
@Entity
@Table(name = "vendor", catalog = "expm")
public class Vendor implements java.io.Serializable {

	private Integer venderId;
	private String venderName;
	private String venderPan;
	private String venderAddress;
	private String venderMobile;
	private String venderEmail;
	private String remarks;
	private BigDecimal vat;
	private BigDecimal serviceTax;
	private Set<Expense> expenses = new HashSet<Expense>(0);
	private Set<Bank> banks = new HashSet<Bank>(0);
	private Set<VendorDocuments> vendorDocumentses = new HashSet<VendorDocuments>(0);

	public Vendor() {
	}

	public Vendor(String venderName) {
		this.venderName = venderName;
	}

	public Vendor(String venderName, String venderPan, String venderAddress, String venderMobile, String venderEmail,
			String remarks, BigDecimal vat, BigDecimal serviceTax, Set<Expense> expenses, Set<Bank> banks,
			Set<VendorDocuments> vendorDocumentses) {
		this.venderName = venderName;
		this.venderPan = venderPan;
		this.venderAddress = venderAddress;
		this.venderMobile = venderMobile;
		this.venderEmail = venderEmail;
		this.remarks = remarks;
		this.vat = vat;
		this.serviceTax = serviceTax;
		this.expenses = expenses;
		this.banks = banks;
		this.vendorDocumentses = vendorDocumentses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "vender_id", unique = true, nullable = false)
	public Integer getVenderId() {
		return this.venderId;
	}

	public void setVenderId(Integer venderId) {
		this.venderId = venderId;
	}

	@Column(name = "vender_name", nullable = false, length = 45)
	public String getVenderName() {
		return this.venderName;
	}

	public void setVenderName(String venderName) {
		this.venderName = venderName;
	}

	@Column(name = "vender_pan", length = 45)
	public String getVenderPan() {
		return this.venderPan;
	}

	public void setVenderPan(String venderPan) {
		this.venderPan = venderPan;
	}

	@Column(name = "vender_address", length = 245)
	public String getVenderAddress() {
		return this.venderAddress;
	}

	public void setVenderAddress(String venderAddress) {
		this.venderAddress = venderAddress;
	}

	@Column(name = "vender_mobile", length = 45)
	public String getVenderMobile() {
		return this.venderMobile;
	}

	public void setVenderMobile(String venderMobile) {
		this.venderMobile = venderMobile;
	}

	@Column(name = "vender_email", length = 45)
	public String getVenderEmail() {
		return this.venderEmail;
	}

	public void setVenderEmail(String venderEmail) {
		this.venderEmail = venderEmail;
	}

	@Column(name = "remarks", length = 245)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "vat", precision = 10)
	public BigDecimal getVat() {
		return this.vat;
	}

	public void setVat(BigDecimal vat) {
		this.vat = vat;
	}

	@Column(name = "service_tax", precision = 10)
	public BigDecimal getServiceTax() {
		return this.serviceTax;
	}

	public void setServiceTax(BigDecimal serviceTax) {
		this.serviceTax = serviceTax;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vendor")
	public Set<Expense> getExpenses() {
		return this.expenses;
	}

	public void setExpenses(Set<Expense> expenses) {
		this.expenses = expenses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vendor")
	public Set<Bank> getBanks() {
		return this.banks;
	}

	public void setBanks(Set<Bank> banks) {
		this.banks = banks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vendor")
	public Set<VendorDocuments> getVendorDocumentses() {
		return this.vendorDocumentses;
	}

	public void setVendorDocumentses(Set<VendorDocuments> vendorDocumentses) {
		this.vendorDocumentses = vendorDocumentses;
	}

}
